version: '3.7'

services:
  server:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/:/app/
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./app/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./app/.env
    ports:
      - 5432:5432

volumes:
    postgres_data:
